# -*- coding: utf-8 -*-
"""aula02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UJUwWUD4C-gcOw4cDh6ueCz3bMmSMOVE
"""

resposta = input('deseja ir a próxima tela')
if resposta == 'sim':
    print('vc foi para outra tela')
else:
    print('vc saiu do sistema')
nome = input('informe o nome de usuário: ')
sexo = input("informe 'F' para o feminino e 'M' para masculino: ").upper()
if(sexo == 'M'):
   sexo = 'o'
elif(sexo == 'F'):
   sexo = 'a'
usuario = int(input('informe o tipo de usuário   \n 1 - para administrador \n 2 - para usuário comum \n 3 - para membro associado'))
if(usuario == 1):
    usuario = 'administrador do sistema'
elif(usuario == 3):
    usuario = 'membro associado'
elif(usuario == 2):
    usuario = 'usuario comum'
else:
    usuario = 'usuario n existente'
print(f'seja bem vind{sexo} {nome}, a sua licença é de {usuario}')

nome = input('informe o nome de usuário: ')
sexo = input("informe 'F' para o feminino e 'M' para masculino: ").upper()
if(sexo == 'M'):
   sexo = 'o'
elif(sexo == 'F'):
   sexo = 'a'
usuario = int(input('informe o tipo de usuário   \n 1 - para administrador \n 2 - para usuário comum \n 3 - para membro associado'))
if(usuario == 1):
    usuario = 'administrador do sistema'
elif(usuario == 3):
    usuario = 'membro associado'
elif(usuario == 2):
    usuario = 'usuario comum'
else:
    usuario = 'usuario n existente'
print(f'seja bem vind{sexo} {nome}, a sua licença é de {usuario}')